name: Trigger auto deployment for tunson

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'Dockerfile/**'
    - '.github/workflows/tunson-AutoDeployTrigger-52879821-fde5-4b42-8ad8-a154ccb446ac.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TUNSON_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}Dockerfile 
          registryUrl: sira34.azurecr.io
          registryUsername: ${{ secrets.TUNSON_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TUNSON_REGISTRY_PASSWORD }}
          containerAppName: tunson
          resourceGroup: DefaultResourceGroup-USW3
          imageToBuild: sira34.azurecr.io/tunson:${{ github.sha }}
          
            

     

